version: "3.9"
services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - CORS_ALLOW=*
      - BACKEND_URL=http://backend:8000
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.1
      # - OPENAI_API_KEY=sk-...
      # - OPENAI_MODEL=gpt-4o-mini
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    entrypoint: ["/bin/sh","-c","/usr/bin/ollama serve & sleep 3 && ollama pull llama3.1 && wait"]

volumes:
  ollama:
